package GameApp;


/**
* GameApp/GameService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDLs/Game.idl
* Monday, 2 June 2025 1:32:45 PM AWST
*/

public interface GameService extends GameServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameService
