package GameApp;


/**
* GameApp/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDLs/Game.idl
* Monday, 2 June 2025 1:32:45 PM AWST
*/

public interface GameServiceOperations 
{
  String login (String username, String password);
  String getUserType (String username);
  String[] startGame (String username);
  boolean guessLetter (String username, char letter);
  String getPartialWord (String username);
  String getLeaderboard ();
  void quitGame (String username);
  void logout (String username);

  // Admin functions
  boolean createPlayer (String username, String password);
  boolean updatePlayer (String username, String newPassword);
  boolean deletePlayer (String username);
  String searchPlayer (String username);
  boolean setGameConfig (int waitTime, int roundDuration);
  String getGameConfig ();
  String checkSessionStatus (String username, String sessionToken);
} // interface GameServiceOperations
