# DO NOT EDIT THIS FILE!
#
# Python module GameApp__POA generated by omniidl

import omniORB
omniORB.updateModule("GameApp__POA")

# ** 1. Stub files contributing to this module
import Game_idl

# ** 2. Sub-modules

# ** 3. End
