package GameApp;

/**
* GameApp/GameServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Sunday, 1 June 2025 7:33:27 PM AWST
*/

public final class GameServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApp.GameService value = null;

  public GameServiceHolder ()
  {
  }

  public GameServiceHolder (GameApp.GameService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApp.GameServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApp.GameServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApp.GameServiceHelper.type ();
  }

}
