package GameApp;


/**
* GameApp/GameServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Sunday, 1 June 2025 7:33:27 PM AWST
*/

public abstract class GameServicePOA extends org.omg.PortableServer.Servant
 implements GameApp.GameServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("startGame", new java.lang.Integer (1));
    _methods.put ("guessLetter", new java.lang.Integer (2));
    _methods.put ("getPartialWord", new java.lang.Integer (3));
    _methods.put ("getLeaderboard", new java.lang.Integer (4));
    _methods.put ("quitGame", new java.lang.Integer (5));
    _methods.put ("logout", new java.lang.Integer (6));
    _methods.put ("createPlayer", new java.lang.Integer (7));
    _methods.put ("updatePlayer", new java.lang.Integer (8));
    _methods.put ("deletePlayer", new java.lang.Integer (9));
    _methods.put ("searchPlayer", new java.lang.Integer (10));
    _methods.put ("setGameConfig", new java.lang.Integer (11));
    _methods.put ("getGameConfig", new java.lang.Integer (12));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // GameApp/GameService/login
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String $result = null;
         $result = this.login (username, password);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // GameApp/GameService/startGame
       {
         String username = in.read_string ();
         String $result[] = null;
         $result = this.startGame (username);
         out = $rh.createReply();
         GameApp.StringSeqHelper.write (out, $result);
         break;
       }

       case 2:  // GameApp/GameService/guessLetter
       {
         String username = in.read_string ();
         char letter = in.read_char ();
         boolean $result = false;
         $result = this.guessLetter (username, letter);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // GameApp/GameService/getPartialWord
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.getPartialWord (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // GameApp/GameService/getLeaderboard
       {
         String $result = null;
         $result = this.getLeaderboard ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // GameApp/GameService/quitGame
       {
         String username = in.read_string ();
         this.quitGame (username);
         out = $rh.createReply();
         break;
       }

       case 6:  // GameApp/GameService/logout
       {
         String username = in.read_string ();
         this.logout (username);
         out = $rh.createReply();
         break;
       }


  // Admin functions
       case 7:  // GameApp/GameService/createPlayer
       {
         String username = in.read_string ();
         String password = in.read_string ();
         boolean $result = false;
         $result = this.createPlayer (username, password);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 8:  // GameApp/GameService/updatePlayer
       {
         String username = in.read_string ();
         String newPassword = in.read_string ();
         boolean $result = false;
         $result = this.updatePlayer (username, newPassword);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 9:  // GameApp/GameService/deletePlayer
       {
         String username = in.read_string ();
         boolean $result = false;
         $result = this.deletePlayer (username);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 10:  // GameApp/GameService/searchPlayer
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.searchPlayer (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 11:  // GameApp/GameService/setGameConfig
       {
         int waitTime = in.read_long ();
         int roundDuration = in.read_long ();
         boolean $result = false;
         $result = this.setGameConfig (waitTime, roundDuration);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 12:  // GameApp/GameService/getGameConfig
       {
         String $result = null;
         $result = this.getGameConfig ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GameApp/GameService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameService _this() 
  {
    return GameServiceHelper.narrow(
    super._this_object());
  }

  public GameService _this(org.omg.CORBA.ORB orb) 
  {
    return GameServiceHelper.narrow(
    super._this_object(orb));
  }


} // class GameServicePOA
