package GameApp;


/**
* GameApp/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Sunday, 1 June 2025 7:33:27 PM AWST
*/

public interface GameServiceOperations 
{
  String login (String username, String password);
  String[] startGame (String username);
  boolean guessLetter (String username, char letter);
  String getPartialWord (String username);
  String getLeaderboard ();
  void quitGame (String username);
  void logout (String username);

  // Admin functions
  boolean createPlayer (String username, String password);
  boolean updatePlayer (String username, String newPassword);
  boolean deletePlayer (String username);
  String searchPlayer (String username);
  boolean setGameConfig (int waitTime, int roundDuration);
  String getGameConfig ();
} // interface GameServiceOperations
