package GameApp;


/**
* GameApp/GameService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Sunday, 1 June 2025 7:33:27 PM AWST
*/

public interface GameService extends GameServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
    String checkSessionStatus(String username, String sessionToken);
} // interface GameService
