# Python stubs generated by omniidl from ..\CORBA_IDLs\Game.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "GameApp"
#
__name__ = "GameApp"
_0_GameApp = omniORB.openModule("GameApp", r"..\CORBA_IDLs\Game.idl")
_0_GameApp__POA = omniORB.openModule("GameApp__POA", r"..\CORBA_IDLs\Game.idl")


# typedef ... StringSeq
class StringSeq:
    _NP_RepositoryId = "IDL:GameApp/StringSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_GameApp.StringSeq = StringSeq
_0_GameApp._d_StringSeq  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_GameApp._ad_StringSeq = (omniORB.tcInternal.tv_alias, StringSeq._NP_RepositoryId, "StringSeq", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_GameApp._tc_StringSeq = omniORB.tcInternal.createTypeCode(_0_GameApp._ad_StringSeq)
omniORB.registerType(StringSeq._NP_RepositoryId, _0_GameApp._ad_StringSeq, _0_GameApp._tc_StringSeq)
del StringSeq

# interface GameService
_0_GameApp._d_GameService = (omniORB.tcInternal.tv_objref, "IDL:GameApp/GameService:1.0", "GameService")
omniORB.typeMapping["IDL:GameApp/GameService:1.0"] = _0_GameApp._d_GameService
_0_GameApp.GameService = omniORB.newEmptyClass()
class GameService :
    _NP_RepositoryId = _0_GameApp._d_GameService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_GameApp.GameService = GameService
_0_GameApp._tc_GameService = omniORB.tcInternal.createTypeCode(_0_GameApp._d_GameService)
omniORB.registerType(GameService._NP_RepositoryId, _0_GameApp._d_GameService, _0_GameApp._tc_GameService)

# GameService operations and attributes
GameService._d_login = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
GameService._d_startGame = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:GameApp/StringSeq:1.0"], ), None)
GameService._d_guessLetter = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_char), (omniORB.tcInternal.tv_boolean, ), None)
GameService._d_getPartialWord = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), None)
GameService._d_getLeaderboard = ((), ((omniORB.tcInternal.tv_string,0), ), None)
GameService._d_logout = (((omniORB.tcInternal.tv_string,0), ), (), None)
GameService._d_createPlayer = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
GameService._d_updatePlayer = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
GameService._d_deletePlayer = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
GameService._d_searchPlayer = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), None)
GameService._d_setGameConfig = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_boolean, ), None)

# GameService object reference
class _objref_GameService (CORBA.Object):
    _NP_RepositoryId = GameService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def login(self, *args):
        return self._obj.invoke("login", _0_GameApp.GameService._d_login, args)

    def startGame(self, *args):
        return self._obj.invoke("startGame", _0_GameApp.GameService._d_startGame, args)

    def guessLetter(self, *args):
        return self._obj.invoke("guessLetter", _0_GameApp.GameService._d_guessLetter, args)

    def getPartialWord(self, *args):
        return self._obj.invoke("getPartialWord", _0_GameApp.GameService._d_getPartialWord, args)

    def getLeaderboard(self, *args):
        return self._obj.invoke("getLeaderboard", _0_GameApp.GameService._d_getLeaderboard, args)

    def logout(self, *args):
        return self._obj.invoke("logout", _0_GameApp.GameService._d_logout, args)

    def createPlayer(self, *args):
        return self._obj.invoke("createPlayer", _0_GameApp.GameService._d_createPlayer, args)

    def updatePlayer(self, *args):
        return self._obj.invoke("updatePlayer", _0_GameApp.GameService._d_updatePlayer, args)

    def deletePlayer(self, *args):
        return self._obj.invoke("deletePlayer", _0_GameApp.GameService._d_deletePlayer, args)

    def searchPlayer(self, *args):
        return self._obj.invoke("searchPlayer", _0_GameApp.GameService._d_searchPlayer, args)

    def setGameConfig(self, *args):
        return self._obj.invoke("setGameConfig", _0_GameApp.GameService._d_setGameConfig, args)

omniORB.registerObjref(GameService._NP_RepositoryId, _objref_GameService)
_0_GameApp._objref_GameService = _objref_GameService
del GameService, _objref_GameService

# GameService skeleton
__name__ = "GameApp__POA"
class GameService (PortableServer.Servant):
    _NP_RepositoryId = _0_GameApp.GameService._NP_RepositoryId


    _omni_op_d = {"login": _0_GameApp.GameService._d_login, "startGame": _0_GameApp.GameService._d_startGame, "guessLetter": _0_GameApp.GameService._d_guessLetter, "getPartialWord": _0_GameApp.GameService._d_getPartialWord, "getLeaderboard": _0_GameApp.GameService._d_getLeaderboard, "logout": _0_GameApp.GameService._d_logout, "createPlayer": _0_GameApp.GameService._d_createPlayer, "updatePlayer": _0_GameApp.GameService._d_updatePlayer, "deletePlayer": _0_GameApp.GameService._d_deletePlayer, "searchPlayer": _0_GameApp.GameService._d_searchPlayer, "setGameConfig": _0_GameApp.GameService._d_setGameConfig}

GameService._omni_skeleton = GameService
_0_GameApp__POA.GameService = GameService
omniORB.registerSkeleton(GameService._NP_RepositoryId, GameService)
del GameService
__name__ = "GameApp"

#
# End of module "GameApp"
#
__name__ = "Game_idl"

_exported_modules = ( "GameApp", )

# The end.
