# DO NOT EDIT THIS FILE!
#
# Python module GameApp generated by omniidl

import omniORB
omniORB.updateModule("GameApp.GameApp")

# ** 1. Stub files contributing to this module
import GameApp.Game_idl

# ** 2. Sub-modules

# ** 3. End
